/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    testImplementation("io.github.tree-sitter:jtreesitter:0.24.0")
}

tasks.register<Exec>("buildNativeLibrary") {
    inputs.dir("src/main/c/tree-sitter")
    inputs.dir("src/main/c/tree-sitter-nix")
    outputs.dir("src/main/resources")

    exec {
        workingDir = file("src/main/c/tree-sitter")
        commandLine("make")
    }

    doLast {
        val sourceFile = file("src/main/c/tree-sitter/libtree-sitter.so")
        val destinationFile = file("src/main/resources/libtree-sitter.so")

        if (sourceFile.exists()) {
            sourceFile.copyTo(destinationFile, overwrite = true)
            println("Native library copied to resources folder.")
        } else {
            throw GradleException("Native library not found after build.")
        }
    }

    workingDir = file("src/main/c/tree-sitter-nix")
    commandLine("gcc", "-shared", "-o", "libtree-sitter-nix.so", "src/parser.c", "src/scanner.c", "-I", "src")

    doLast {
        val sourceFile = file("src/main/c/tree-sitter-nix/libtree-sitter-nix.so")
        val destinationFile = file("src/main/resources/libtree-sitter-nix.so")

        if (sourceFile.exists()) {
            sourceFile.copyTo(destinationFile, overwrite = true)
            println("Native library copied to resources folder.")
        } else {
            throw GradleException("Native library not found at ${sourceFile.absolutePath} after build.")
        }
    }
}

tasks.named("processResources") {
    dependsOn("buildNativeLibrary")
}

tasks.withType<JavaExec> {
    environment("LD_LIBRARY_PATH", "/home/lh/src/truffle-nix/tree-sitter-nix/src/main/resources")
}
