name: Run Benchmarks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up library path for native libraries
        run: echo "LD_LIBRARY_PATH=$(pwd)/tree-sitter-nix/src/main/resources" >> $GITHUB_ENV

      - name: Run JMH benchmarks with Gradle
        run: ./gradlew :truffle-nix:jmh

      - name: Upload benchmark results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: truffle-nix/build/reports/jmh/